Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/SpaceInsidePercentLiteralDelimiters:
  EnforcedStyle: space

Layout/TrailingBlankLines:
  Enabled: false

# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 66
  Exclude:
    - 'spec/**/*'

# Configuration parameters: EnforcedStyle.
# SupportedStyles: braces, no_braces, context_dependent
Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces
  Exclude:
    - 'spec/**/*'

Style/CaseEquality:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'